# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_at', models.DateTimeField(blank=True, null=True)),
                ('schoolid', models.CharField(blank=True, max_length=250, null=True)),
                ('subjectid', models.CharField(blank=True, max_length=50, null=True)),
                ('studentid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
